server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**,/api/users/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
        - id: task-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/task/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
  data:
    redis:
      host: localhost
      port: 6379

logging:
    level:
      org.hibernate: ERROR
      org.hibernate.SQL: OFF
      org.hibernate.type.descriptor.sql: OFF
    file:
      name: logs/api-gateway.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%-5level] ${spring.application.name} - %msg%n"
