apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: task-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
            - containerPort: 8081